id: git_push
namespace: wbr-automation
description: Save and Execute the flow

inputs:
  - id: env
    type: STRING
    defaults: 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


tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.PushFlows
    username: Akhilesh-Gollangi
    password: "{{inputs.env}}"
    url: https://github.com/Akhilesh-Gollangi/kestra_codes
    branch: develop
    flows:
      - hello_world
    sourceNamespace: wbr1
    targetNamespace: prod
    gitDirectory: yml
    commitMessage: "changes to kestra flows"
    dryRun: false


triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"
    disabled: true
